# Auto-generated by .github/workflows/release.yml on each tagged release.
# The version, urls, and sha256 values are overwritten there; do not edit by hand.
class Mind < Formula
  desc "Manager for agent tooling: skills, agents, rules, and tools"
  homepage "https://github.com/jaemk/mind"
  version "0.17.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/jaemk/mind/releases/download/v0.17.0/mind-0.17.0-aarch64-apple-darwin.tar.gz"
      sha256 "6eeab7650106f79e53fe0d9c58028db95b641f85f87cb263c5ba62339fa7a657"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/jaemk/mind/releases/download/v0.17.0/mind-0.17.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "7c1280ed8b45036376ce868fc2f079217232ac78358209f0533ad76d556403a1"
    end
    on_intel do
      url "https://github.com/jaemk/mind/releases/download/v0.17.0/mind-0.17.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "83eebd1d3b5708c44757d0daafccbecdadfd8a520a1b2169aa535f616c88b41d"
    end
  end

  def install
    bin.install "mind"
  end

  test do
    system "#{bin}/mind", "--version"
  end
end
